name: Checkmarx CxGo Scan
on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@docker-image #Github Action version
      with:
        project: GithubActionCxGoTest-MP
        team: \Demo\CxFlow\MithileshPawar
        cxgo_client_secret: ${{ secrets.CX_GO_CLIENT_SECRET }}
        cxgo_base_url: https://api.checkmarx.net
        cxgo_portal_url: https://cloud.checkmarx.net
        break_build: false
        scanners: cxgo
        bug_tracker: Sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
