name: Checkmarx SCA Scan
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    env :
        REPO_NAME: ${{ github.event.repository.name }}
    steps:
    - name: Get the Organization Name
      run: echo "ORG_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@docker-image #Github Action version
      with:
        project: GithubActionSCAScanTest-MP
        team: /CxServer/MP
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: sca-champions
        sca_username: ${{ secrets.CX_SCA_USERNAME }}
        sca_password: ${{ secrets.CX_SCA_PASSWORD }}
        break_build: false
        scanners: sca
        github_token: ${{ secrets.GH_TOKEN }}
        params: --repo-url="https://github.com/MithileshPawar/BodgeIt.git" --logging.level.com.checkmarx.flow.custom=TRACE --logging.level.com.checkmarx.flow.cmd=TRACE --logging.level.com.checkmarx.flow.service=TRACE --logging.level.com.checkmarx.flow.controller=TRACE  --logging.level.org.springframework.web.client.RestTemplate=TRACE --logging.level.com.checkmarx.flow.config=TRACE  --namespace=${{ env.ORG_NAME }} --repo-name=${{ env.REPO_NAME }}  --branch=${{ github.ref	}}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

