name: Checkmarx SAST Scan
on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: GithubActionSASTTest-MP
        team: \Demo\CxFlow\MithileshPawar
        cxgo_client_secret: ${{ secrets.CX_GO_CLIENT_SECRET }}
        cxgo_base_url: https://api.checkmarx.net
        cxgo_portal_url: https://cloud.checkmarx.net
        break_build: false
        scanners: cxgo
        bug_tracker: Csv
        params: --csv.file-name-format="[TEAM]-[PROJECT].csv" --csv.data-folder="./" --csv.include-header=true



