name: Checkmarx SAST Scan with CSV
on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0 #Github Action version
      with:
        project: GithubActionSASTTest-MP
        team: CxServer\SP\Checkmarx\Mithilesh
        checkmarx_url: https://ast.dev.checkmarx-ts.com
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: false
        params: --bug-tracker=Csv --bug-tracker-impl=Csv --csv.file-name-format="[TEAM]-[PROJECT].csv" --csv.data-folder="./" --csv.include-header=true



