name: Checkmarx SAST Scan
on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: GithubActionSASTTest-MP
        team: /CxServer/MP
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: sca-champions
        sca_username: ${{ secrets.CX_SCA_USERNAME }}
        sca_password: ${{ secrets.CX_SCA_PASSWORD }}
        break_build: false
        scanners: sca 
        bug_tracker: Csv
        params: --csv.file-name-format="[TEAM]-[PROJECT].csv" --csv.data-folder="./" --csv.include-header=true



