name: Checkmarx AST CLI
on:
  push:
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx AST CLI
      uses: MithileshPawar/ast-github-action@master #Github Action version
      with:
        base_uri: http://master.astcloud.net
        client_id: ${{ secrets.AST_MASTER_CLIENT }}
        secret: ${{ secrets.AST_MASTER_SECRET }}
        additional_params: --incremental true
