name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: GithubActionAST-MP
        ast_api_url: http://ec2-3-249-214-110.eu-west-1.compute.amazonaws.com
    #   ast_webapp_url: http://cx-ast-testing.dev.checkmarx-ts.com
        ast_client_id: CxFlow
        ast_client_secret: ${{ secrets.AST_CLIENT_SECRET }}
        break_build: false
        scanners: ast
        bug_tracker: Sarif
        params:
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

