name: Checkmarx SCA Scan
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    env :
        REPO_NAME: ${{ github.event.repository.name }}
    steps:
    - name: Get the Organization Name
      run: echo "ORG_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x #Github Action version
      with:
        project: GithubActionTest
        team: ${{ secrets.CX_TEAM }}
        checkmarx_url: ${{ secrets.CX_SERVER }}
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: true
        github_token: ${{ secrets.GH_TOKEN }}
        params: --logging.level.com.checkmarx.flow.custom=TRACE --logging.level.com.checkmarx.flow.cmd=TRACE --logging.level.com.checkmarx.flow.service=TRACE --logging.level.com.checkmarx.flow.controller=TRACE  --logging.level.org.springframework.web.client.RestTemplate=TRACE --logging.level.com.checkmarx.flow.config=TRACE --bug-tracker=GitHub --namespace=${{ env.ORG_NAME }} --repo-name=${{ env.REPO_NAME }}  --branch=${{ github.ref	}}  --enabled-vulnerability-scanners=sca --repo-url="https://github.com/MithileshPawar/BodgeIt.git" --sca.appUrl= ${{ secrets.CX_SCA_APP_URL }} --sca.apiUrl= ${{ secrets.CX_SCA_API_URL }} --sca.password = ${{ secrets.CX_SCA_PASSWORD }} --sca.username = ${{ secrets.CX_SCA_USERNAME }} --sca.tenant = ${{ secrets.CX_SCA_TENANT }} --sca.accessControlUrl = ${{ secrets.CX_SCA_AC_URL }}


#--logging.level.org.apache.http.wire=DEBUG 
