name: Checkmarx SAST Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - main    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@docker-image #Github Action version
      with:
        project: GithubActionSASTTest-MP
        team: /CxServer/MP
        checkmarx_url: http://cx9xshard5.dev.checkmarx-ts.com
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: false
        scanners: sast
        bug_tracker: GITHUBPULL
        params: --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }}
