name: Checkmarx SAST Scan
on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0
      with:
        project: GithubActionTest
        team: ${{ secrets.CX_TEAM }}
        checkmarx_url: ${{ secrets.CX_SERVER }}
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: true
        github_token: ${{ secrets.GH_TOKEN }}
        params: --logging.level.com.checkmarx.flow.cmd=TRACE --logging.level.com.checkmarx.flow.service= TRACE --logging.level.com.checkmarx.flow.controller= TRACE
    # Upload SARIF report for CodeQL / Security Alerts PRocessing
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

