name: Checkmarx SAST Scan
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    env :
        REPO_NAME: ${{ github.event.repository.name }}
    steps:
    - name: Get the Organization Name
      run: echo "ORG_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@feature/integrate-scanners #Github Action version
      with:
        project: GithubActionSASTTest
        team: /CxServer/MP
        checkmarx_url: http://cx9xshard5.dev.checkmarx-ts.com
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: false
        scanners: sast
        github_token: ${{ secrets.GH_TOKEN }}
        params: --logging.level.com.checkmarx.flow.custom=TRACE --logging.level.com.checkmarx.flow.cmd=TRACE --logging.level.com.checkmarx.flow.service=TRACE --logging.level.com.checkmarx.flow.controller=TRACE  --logging.level.org.springframework.web.client.RestTemplate=TRACE --logging.level.com.checkmarx.flow.config=TRACE  --namespace=${{ env.ORG_NAME }} --repo-name=${{ env.REPO_NAME }}  --branch=${{ github.ref	}}  --repo-url="https://github.com/MithileshPawar/BodgeIt.git"

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

