name: Checkmarx SAST Scan
on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0
      with:
        project: GithubActionTest
        team: ${{ secrets.CX_TEAM }}
        checkmarx_url: ${{ secrets.CX_SERVER }}
        checkmarx_username: ${{ secrets.CX_USER }}
        checkmarx_password: ${{ secrets.CX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        break_build: true
        github_token: ${{ secrets.GH_TOKEN }}
        params: --logging.level.com.checkmarx.flow.cmd=DEBUG --logging.level.com.checkmarx.flow.service=DEBUG --logging.level.com.checkmarx.flow.controller=DEBUG --logging.level.org.apache.http.wire=DEBUG  --logging.level.org.springframework.web.client.RestTemplate=DEBUG --bug-tracker=GitHub --namespace=MithileshPawar --repo-name=BodgeIt --branch=master


