name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@feature/AST-4073-remove_apikey #Github Action version
        with:
          project_name: GHAction_AG_BodgeItTeste
          cx_tenant: organization
          base_uri: https://ast-master.dev.cxast.net/ 
          cx_apikey: ${{ secrets.CX_APIKEY }}
          additional_params: -v --sast-preset-name High --scan-types kics
